export const asyncTypes = Object.freeze({
    CREATE_POST_ASYNC: 'CREATE_POST_ASYNC',
    REMOVE_POST_ASYNC: 'REMOVE_POST_ASYNC',
    LIKE_POST_ASYNC:   'LIKE_POST_ASYNC',
    UNLIKE_POST_ASYNC: 'UNLIKE_POST_ASYNC',
});
