export const types = Object.freeze({
    EMIT_ERROR:                 'EMIT_ERROR',
    INITIALISE:                 'INITIALISE',
    INITIALISE_SUCCESS:         'INITIALISE_SUCCESS',
    SET_ONLINE_STATE:           'SET_ONLINE_STATE',
    SET_POSTS_FETCHING_STATE:   'SET_POSTS_FETCHING_STATE',
    SET_AUTH_FETCHING_STATE:    'SET_AUTH_FETCHING_STATE',
    SET_PROFILE_FETCHING_STATE: 'SET_PROFILE_FETCHING_STATE',
    SET_PROFILE_EDITING_STATE:  'SET_PROFILE_EDITING_STATE',
    SET_AVATAR_FETCHING_STATE:  'SET_AVATAR_FETCHING_STATE',
    SET_PASSWORD_EDITING_STATE: 'SET_PASSWORD_EDITING_STATE',
});
