export const types = Object.freeze({
    SET_ONLINE_STATE:         'SET_ONLINE_STATE',
    SET_POSTS_FETCHING_STATE: 'SET_POSTS_FETCHING_STATE',
    SET_AUTH_FETCHING_STATE:  'SET_AUTH_FETCHING_STATE',
});
