export const types = Object.freeze({
    INITIALISE:               'INITIALISE',
    INITIALISE_SUCCESS:       'INITIALISE_SUCCESS',
    SET_ONLINE_STATE:         'SET_ONLINE_STATE',
    SET_POSTS_FETCHING_STATE: 'SET_POSTS_FETCHING_STATE',
    SET_AUTH_FETCHING_STATE:  'SET_AUTH_FETCHING_STATE',
});
